# Generated by Django 3.1.6 on 2021-02-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.blog'),
            preserve_default=False,
        ),
    ]
