# Generated by Django 3.1.6 on 2021-02-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='projects_data',
        ),
    ]
