# Generated by Django 3.1.6 on 2021-02-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210217_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organisation', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
