# Generated by Django 3.1.6 on 2021-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_experience_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='education_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=120)),
                ('clg_name', models.CharField(max_length=120)),
                ('uni_name', models.CharField(max_length=120)),
                ('passing', models.DateField()),
                ('marks', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
