# Generated by Django 3.1.6 on 2021-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_about_me_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='extra_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField()),
            ],
        ),
    ]
